[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "arg-ai"
version = "26.1.19.1"
requires-python = ">=3.10"
dependencies = [
  "psycopg[binary]==3.2.3",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
